name: 获取最新脚本
on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-zero205-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lukeys-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lukesyy/glados_automation.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
